### PR TITLE
Naming sidebar actions and communities

### PR DESCRIPTION
**Pull request by ail3ngrimaldi**
This PR closes issues #76  #108 and #106 

Mobile:
image

Desktop:
image

### CODE REVIEW

**Comment by olanod** [comment]
I like it for the communities but not so sure about the profile and the actions, I also see some issues with the layout while testing locally

**Comment by ail3ngrimaldi** [comment]
I agree that it seems a bit odd, but I added them because I thought that at first glance, it’s not so obvious which action corresponds to each icon.
Also, the communities could be easily identified with a profile picture, but as I understand, it's not mandatory for them to have one, am I right?

That said, should I remove the labels from the actions?

**Comment by S0c5** [comment]
@olanod @ail3ngrimaldi  any comments on this? what is it left to close and merge?

**Comment by ail3ngrimaldi** [comment]
@olanod updated!

**Review by olanod — APPROVED** [review]

**Pull request merged**
